## This is a yaml file, defining options for specific rules or by default.
## The '#' defines a comment.
## the two spaces at the beginning of rows below rulenames are important.
## For more information see https://snakemake.readthedocs.io/en/stable/executing/cluster-cloud.html#cluster-execution
## Additional options not covered here can be found at https://snakemake.readthedocs.io/en/stable/executing/cli.html#execution

## Ripped the below code under "Workflow Profile Examples" from the site: https://gcxgce.sharepoint.com/teams/1000645/SitePages/Snakemake-GPSC-Documentation.aspx

######################
### Basic Commands ###
######################
cores: 25 # total number of cores you want snakemake to request at any time.
jobs: 20  # max amount of jobs to run at once.
latency-wait: 60 # gives time for containers to start and for other I/O delays
rerun-incomplete: true
# quiet: false
retries: 0 # useful for certain systems.
max-jobs-per-second: 20 # not sure how necessary but probably not a bad idea....
# max-threads:
executor: cluster-generic
cluster-generic-submit-cmd: "workflow/scripts/slurm_jobscript.py" # I believe this command allows us to specify how the below is submitted to the cluster
# cluster-cancel: scancel   # doesn't seem to work...
 
 
#############
### SLURM ###
#############
# slurm: true
default-resources: 
  slurm_account: aafc_aac
  slurm_partition: standard
  runtime: 5  # integer defines minutes
  nodes: 1
  ntasks: 4
  mail_user: xander.fleury@agr.gc.ca
  mail_type: END,FAIL
  # - slurm_extra=" "
 
 
#############
### Conda ###
#############
use-conda: True
# conda-cleanup-envs: true
# conda-cleanup-pkgs: 
# conda-frontend: mamba   # can use conda IF mamba is not installed. 
 
 
###################
### Env Modules ###
###################
# use-envmodules: true
# envmodules: "environments/slurmmake_env.yaml"
 
 
#######################
### Resource Scopes ###
#######################
# Affects how Snakemake defines Resource Limits. 
# Note cores and threads are ALWAYS considered local...
# set-resource-scopes:
#     cores: local
 

########################
### Containerization ###
########################
# use-singularity: true
# singularity-prefix-dir:
# singularity-args:
# cleanup-containers: false
 
 
#################################
### TroubleShooting / Testing ###
#################################
forceall: true # turn on for testing forces all jobs to be re-run. 
# verbose: true # use for debugging. 
# debug: true  # used for debugging.
# nolock: false
# stats: false
# debug-dag: false
# printshellcmds: true
# delete-all-output: false
# delete-temp-output: false
# list-untracked: false
# list-params-changes: false
# summary: false
# detailed-summary: false
#report: # add a specific file for this if you would like it. 
 
 
#############################
### Rule Specific Configs ###
#############################
# Just add the variation you would like for the rule
# Review the snakemake documentation if you are unsure of a specific option. 
# https://snakemake.readthedocs.io/en/stable/executing/cli.html#execution
# set-threads:
#  trimming: 4 # 4 is optimal for fastp in all tested cases (2, 4, 8, 16, 32). 
# set-resources:
#  trimming:
#    slurm_account: <gpu account>   # Example but unnecessary here
#    slurm_partition: <gpu_partition>              # Example but unnecessary here
# set-scatter:
# set-resource-scope:
